name: Run E2E Tests

on: [pull_request]

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    services:
      api-test-pg:
        container_name: 
        api-test-pg
        image: bitnami/postgresql
        ports:
          - 5432:5432
        env:
          POSTGRESQL_USER: docker
          POSTGRESQL_PASSWORD: docker
          POSTGRESQL_DB: api-test

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - run: npm ci

      - run: npm run test:e2e
        env:
          DATABASE_URL: 'postgresql://docker:docker@localhost:5432/api-test'
